# ใช้ Node.js 20 เป็น Base Image
FROM node:20-alpine

# กำหนดโฟลเดอร์ทำงาน
WORKDIR /app

# คัดลอกไฟล์ package.json และ lockfile
COPY package*.json ./

# ติดตั้ง Dependencies
RUN npm install --only=production

# คัดลอกโค้ดทั้งหมด
COPY . .

# Build Nuxt สำหรับ Production
RUN npm run build

# เปิดพอร์ต 3000
EXPOSE 3000

# ใช้ Nuxt Preview Mode แทน Nginx
CMD ["npm", "run", "preview"]
